// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAMZENiAeNIRhAYD1f87WCow5QYTYGL34',
    appId: '1:1029043609628:android:4b4c4ba808a3956becbfd9',
    messagingSenderId: '1029043609628',
    projectId: 'subscription-auditor-75577',
    storageBucket: 'subscription-auditor-75577.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADdPJvI-RLFNcuwn7Yo6_giPIo5PLb6pw',
    appId: '1:1029043609628:ios:7a0fa87530d6d498ecbfd9',
    messagingSenderId: '1029043609628',
    projectId: 'subscription-auditor-75577',
    storageBucket: 'subscription-auditor-75577.firebasestorage.app',
    iosClientId: '1029043609628-vd2bc7idu3v1j11tnl6ktl9lbsto9rf1.apps.googleusercontent.com',
    iosBundleId: 'com.example.subscriptionAuditor',
  );
}
